language: java

dist: trusty

branches:
  only:
    - master

sudo: false

before_install:
  - cd $HOME
  - (git clone https://github.com/kframework/k || true)
  - cd k
  - git fetch --all
  - git checkout master
  - mvn package -DskipTests;
  - export PATH=$PATH:$(pwd)/k-distribution/target/release/k/bin
  - cd $TRAVIS_BUILD_DIR

cache:
  directories:
    - $HOME/k
    - !$HOME/k/k-distribution/target/archive-tmp
    - $HOME/.m2

install:
  - make

script:
  - cd test
  - ktest config.xml

notifications:
  email:
    recipients:
    - tosun2@illinois.edu
    - lpena7@illinois.edu
    on_success: change # default: change
    on_failure: always # default: always
  slack: formal-systems-lab:2Yic9kM7aEPTLX3Ti4AklBmL
  slack:
    on_success: change
    on_failure: always
